/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX Engine
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SpeakerSupportPermittedSynthesisMorphing } from './SpeakerSupportPermittedSynthesisMorphing';
import {
    SpeakerSupportPermittedSynthesisMorphingFromJSON,
    SpeakerSupportPermittedSynthesisMorphingFromJSONTyped,
    SpeakerSupportPermittedSynthesisMorphingToJSON,
} from './SpeakerSupportPermittedSynthesisMorphing';

/**
 * 
 * @export
 * @interface 
 */
export interface  {
    /**
     * 
     * @type {SpeakerSupportPermittedSynthesisMorphing}
     * @memberof 
     */
    permittedSynthesisMorphing?: SpeakerSupportPermittedSynthesisMorphing;
}

/**
 * Check if a given object implements the  interface.
 */
export function instanceOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FromJSON(json: any):  {
    return FromJSONTyped(json, false);
}

export function FromJSONTyped(json: any, ignoreDiscriminator: boolean):  {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'permittedSynthesisMorphing': !exists(json, 'permitted_synthesis_morphing') ? undefined : SpeakerSupportPermittedSynthesisMorphingFromJSON(json['permitted_synthesis_morphing']),
    };
}

export function ToJSON(value?:  | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'permitted_synthesis_morphing': SpeakerSupportPermittedSynthesisMorphingToJSON(value.permittedSynthesisMorphing),
    };
}

